version: "3.8"
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb_llm_mas_consistency
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass1
    volumes:
      - mongodb-data-llm-mas-consistency:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_llm_mas_consistency
    ports:
      - "5672:5672"  # RabbitMQ broker port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data-llm-mas-consistency:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s


volumes:
  rabbitmq-data-llm-mas-consistency:
  mongodb-data-llm-mas-consistency: